name: LaserTagged
version: '${version}'
main: com.th7bo.lasertagged.LaserTagged
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  testing:
    description: Testing command
    usage: /<command>